ham:
  site_icon: https://raw.githubusercontent.com/googlefonts/noto-emoji/main/svg/emoji_u1f969.svg
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
  - jekyll-readme-index
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
tagline: The truly static, Git-based wiki project
title: HAM
theme: jekyll-ham
url: ./
readme_index:
  with_frontmatter: true